<?php

/**
 * @file
 * Generates PDF of order invoice and sends as attachment in mail.
 */

require_once DRUPAL_ROOT . '/vendor/autoload.php';

use Drupal\Core\File;
use Dompdf\Dompdf;

function uc_pdf_invoice_mail_mail_alter(&$message) {
 if (strpos($message['id'], 'uc_order_action-mail') !== FALSE) {
	$body        = $message['body'];
	$invoiceData = implode("", $body);
	if (!empty($invoiceData)) {
      $dompdf = new Dompdf();
      $dompdf->loadHtml($invoiceData);
      $dompdf->render();

      $filename     = tempnam('temporary://', 'invoice_') . '.pdf';
      $output    = $dompdf->output();
      file_put_contents($filename, $output);

      $filesystem = \Drupal::service('file_system');
      $pdf = \Drupal\file\Entity\File::create();
	  $pdf->setFileUri($filename);
	  $pdf->setOwnerId(1);
	  $pdf->setMimeType(\Drupal::service('file.mime_type.guesser')->guess($file_name));
	  $pdf->setFileName($filesystem->basename($filename));
	  $pdf->setPermanent();
	  $pdf->save();

      $pdf_attachment  = array(
          'filecontent' => file_get_contents($pdf->getFileUri()),
          'filemime' => $pdf->getMimeType(),
          'filename' => 'invoice.pdf',
      );

      $message['params']['attachment'] = $pdf_attachment;
      uc_pdf_invoice_mail_add_attachment($message);
    }
 }
}

/**
 * Update Message ContentType.
 */
function uc_pdf_invoice_mail_add_attachment(array &$message) {
  if (!empty($message['params']['attachment'])) {
    $params = $message['params'];
    $attachment = $params['attachment'];
    $filename = basename($attachment['filename']);
    $filecontent = $attachment['filecontent'];
    $content = chunk_split(base64_encode($filecontent));
    $uid = md5(uniqid(time()));

    $messageHeader = &$message['headers'];
    $originalContentType = $messageHeader['Content-Type'];
    $messageHeader['Content-Type'] = "multipart/mixed; boundary=\"$uid\"";

    $header = "This is a multi-part message in MIME format.\r\n";
    $header .= "--$uid\r\n";
    $header .= "Content-Type: $originalContentType \r\n\r\n";
    $header .= wordwrap(implode('', $message['body'])) . "\r\n\r\n";
    $header .= "--$uid\r\n";
    $header .= "Content-Type: $attachment[filemime];
              name=\"" . $filename . "\"\r\n";
    $header .= "Content-Transfer-Encoding: base64\r\n";
    $header .= "Content-Disposition: attachment;
              filename=\"" . $filename . "\"\r\n\r\n";
    $header .= $content . "\r\n\r\n";
    $header .= "--$uid--";
    $message['body'] = [$header];
  }
}
